contrib/bindings/go/pathrs/pathrs.go, examples/go/cat.go
Hello @cyphar, that is a great crate.
This PR is going to close #3 
I was tried to have done it with considerable safety but I am not sure, that I accomplished that :)
Not covered features (still have not managed all the information profoundly)
* duplicate
* from_fd
* intofd
I would like to mention that it was barely tested, I might should write a bunch of tests.
=> Golang binding

.github/workflows/ci.yml, Cargo.toml, cbindgen.toml, contrib/bindings/python/pathrs.py, go-pathrs/libpathrs_linux.go, go-pathrs/procfs_linux.go, include/pathrs.h, src/capi/core.rs, src/capi/mod.rs, src/capi/procfs.rs, src/capi/ret.rs, src/error.rs, src/handle.rs, src/lib.rs, src/procfs.rs, src/resolvers/mod.rs, src/resolvers/opath.rs, src/resolvers/procfs.rs, src/syscalls.rs, src/tests/common/mntns.rs, src/tests/common/mod.rs, src/tests/mod.rs, src/tests/test_procfs.rs, src/tests/test_resolve.rs, src/utils.rs
A toy example of using this API to do a few operations runc needs to do internally: 
```c
int get_self_exe()
{
/* This follows the trailing magic-link! */
int fd = pathrs_proc_open(PATHRS_PROC_SELF, "exe", O_PATH);
if (fd < 0) {
pathrs_error_t *error = pathrs_errorinfo(fd);
/* ... print the error ... */
pathrs_errorinfo_free(error);
return -1;
}
return fd;
}
int write_apparmor_label(char *label)
{
int fd, err, saved_errno = 0;
fd = pathrs_proc_open(PATHRS_PROC_SELF, "attr/exec", O_WRONLY|O_NOFOLLOW);
if (fd < 0) {
pathrs_error_t *error = pathrs_errorinfo(fd);
/* ... print the error ... */
pathrs_errorinfo_free(error);
return -1;
}
err = write(fd, label, strlen(label));
close(fd);
return err;
}
char *get_unsafe_path(int fd)
{
char *fdpath;
if (asprintf(&fdpath, "fd/%d", fd) < 0)
return …
```
=> procfs: add safe procfs API and harden proc operations

.github/workflows/rust.yml, Cargo.toml, examples/rust-cat/main.rs, src/capi/core.rs, src/capi/procfs.rs, src/capi/ret.rs, src/capi/utils.rs, src/error.rs, src/flags.rs, src/handle.rs, src/lib.rs, src/procfs.rs, src/resolvers/mod.rs, src/resolvers/opath/impl.rs, src/resolvers/opath/mod.rs, src/resolvers/opath/symlink_stack.rs, src/resolvers/openat2.rs, src/resolvers/procfs.rs, src/root.rs, src/syscalls.rs, src/tests/common/mntns.rs, src/tests/test_resolve.rs, src/tests/test_root_ops.rs, src/utils/fd.rs, src/utils/path.rs, src/utils/umask.rs
This version was released in 2022, so it should be old enough to use for
packaging in regular distributions.
Ideally we would try to use Rust 1.63 (the version in Debian stable),
but the main thing limiting us is std::backtrace::Backtrace. We do plan
to rework errors in the future (to avoid a bunch of the issues with
snafu), so we might make be able to get to 1.63 in the future.
We can't really go older than 1.63 because rustix requires it (likely
because of the BorrowedFd io_safety API), which we plan to migrate to as
well.
=> rust: drop MSRV to 1.63

contrib/bindings/python/pathrs/_pathrs.py, go-pathrs/libpathrs_linux.go, go-pathrs/root_linux.go, include/pathrs.h, src/capi/core.rs, src/root.rs, src/tests/test_root_ops.rs, src/utils/dir.rs, src/utils/mod.rs
Implement `Root::remove_all` and split `Root::remove` so that we don't have the unnecessary retry logic.
Fixes #11
=> root: implement remove_all and fix up removal methods

src/capi/core.rs, src/capi/procfs.rs, src/capi/ret.rs, src/handle.rs, src/procfs.rs, src/resolvers/mod.rs, src/resolvers/opath/impl.rs, src/resolvers/opath/symlink_stack.rs, src/resolvers/openat2.rs, src/resolvers/procfs.rs, src/root.rs, src/syscalls.rs, src/tests/common/mntns.rs, src/tests/test_resolve.rs, src/tests/test_root_ops.rs, src/utils/dir.rs, src/utils/fd.rs, src/utils/path.rs, src/utils/umask.rs
This ensures we encode all of the lifetime rules we care about for file
descriptors in a much cleaner way. Most of this was a fairly
straightforward migration from File/RawFd -> AsFd, but there were a few
other notable things:
* We now have RootRef and HandleRef to represent borrowed versions of
Root and Handle. This was needed for our C FFI (which takes a
BorrowedFd now), but is also an improvement in usability for library
users. Previously we used ManuallyDrop to avoid closing the passed
file descriptors in C FFI. This is much more ergonomic.
Unfortunately, we would like to be able to implement Deref (to allow
Root and Handle to share methods of RootRef and HandleRef).
Unfortunately, because they are structures that take lifetimes rather
than plain references it seems it is not possible …
=> *: migrate to OwnedFd/BorrowedFd

CHANGELOG.md, src/capi/procfs.rs, src/error.rs, src/procfs.rs, src/resolvers/opath/impl.rs, src/tests/common/root.rs, src/tests/test_resolve.rs, src/tests/test_resolve_partial.rs, src/utils/mod.rs, src/utils/sysctl.rs
Because we resolve symlinks in userspace, fs.protected_symlinks doesn't
get applied by the kernel to our lookups. While it's not really clear
whether this is really necessary for scoped lookups, for consistency we
should just emulate may_follow_link().
Unfortunately, checking fs.protected_symlinks requires looking at
/proc/sys which can't be done with the currently-exposed ProcfsHandle
API so we have to create a private API for that (until we come up with a
nicer one for users to use). This also means that we can no longer apply
"subset=pid" to fsopen-based procfs handles.
Fixes #58
=> opath resolver: implement fs.protected_symlinks emulation

CHANGELOG.md, src/flags.rs, src/lib.rs, src/procfs.rs, src/resolvers/mod.rs, src/resolvers/procfs.rs, src/root.rs, src/tests/capi/root.rs, src/tests/test_resolve.rs, src/tests/test_resolve_partial.rs, src/tests/test_root_ops.rs, src/tests/traits/root.rs
This is modelled after a builder pattern, and it allows some for more
erngomic usage of flags in one-liners and temporarily for a few
commands.
```rust
let root = Root::open(rootdir)?;
// Apply ResolverFlags::NO_SYMLINKS for a single operation.
root.as_ref()
.with_resolver_flags(ResolverFlags::NO_SYMLINKS)
.mkdir_all("foo/bar/baz", &perm)?;
// Create a temporary RootRef to do multiple operations.
let root2 = root
.as_ref()
.with_resolver_flags(ResolverFlags::NO_SYMLINKS);
root2.create("one", &InodeType::Directory(perm))?;
root2.remove_all("foo")?;
```
Fixes #24
=> root: move to get/set model for configuring resolver flags

Cargo.toml, src/lib.rs, src/utils/umask.rs
This patch changes the implementation of `get_umask_procfs` to avoid the dependency on the `regex` crate.
The original expression `^Umask:\s*(0[0-7]+)$` is implemented as:
```rust
if let Some(umask) = line.strip_prefix("Umask:") {
return Ok(mode_t::from_str_radix(umask.trim(), 8).ok());
}
```
The previous code was using `expect` to get the result from `from_str_radix`. Now it just converts the `Result` from `from_str_radix` to an `Option`. The logic is different, but the behaviour is the same:
* If the value is correct (like `Umask: 0022`), both `Ok(Some(from_str_radix().expect()))` and  `Ok(from_str_radix().ok())` returns the same value.
* If the value is unexpected (like `Umask: 0999`),
* The previous code will ignore the line (it does not match the regular expression), and will return …
=> Manual parser for umask values.

CHANGELOG.md, Cargo.toml, contrib/bindings/python/pathrs/_pathrs.py, go-pathrs/libpathrs_linux.go, go-pathrs/procfs_linux.go, include/pathrs.h, src/capi/procfs.rs, src/procfs.rs, src/resolvers/opath/impl.rs, src/tests/common/mntns.rs, src/tests/test_procfs.rs, src/utils/sysctl.rs
The semantics are the same as the other bases, except that in the
fsopen() case we will have to create a temporary instance for the
operation.
We want to set subset=pid,hidepid=ptraceable for the global procfs
handle (to restrict the scope if the handle was leaked into a
container). Unfortunately we also need to access stuff outside of
/proc/$pid such as sysctls (/proc/sys/*), and we plan to allow users to
access stuff in the root of /proc eventually.
So, in order to balance these two requirements, we can just create a
temporary procfs handle whenever we need to access stuff outside of the
root (which should be far more rare than accessing things inside
/proc/$pid) and use it as a fallback if the global procfs handle return
ENOENT. This will increase the overhead of accessing stuff …
=> procfs: add support for ProcfsBase::ProcRoot

CHANGELOG.md, Cargo.toml, contrib/bindings/python/pyproject.toml
```md
> 頒布と聞いたら蛇に睨まれた蛙になるよ
- procfs: add support for operating on files in the `/proc` root (or other
processes) with `ProcfsBase::ProcRoot`.
While the cached file descriptor shouldn't leak into containers (container
runtimes know to set `PR_SET_DUMPABLE`, and our cached file descriptor is
`O_CLOEXEC`), I felt a little uncomfortable about having a global unmasked
procfs handle sitting around in `libpathrs`. So, in order to avoid making a
file descriptor leak by a `libpathrs` user catastrophic, `libpathrs` will
always try to use a "limited" procfs handle as the global cached handle
(which is much safer to leak into a container) and for operations on
`ProcfsBase::ProcRoot`, a temporary new "unrestricted" procfs handle is
created just for that operartion. This is more expensive, but it …
```
=> VERSION: release 0.1.1

.github/workflows/bindings-c.yml, .github/workflows/bindings-go.yml, .github/workflows/bindings-python.yml, .github/workflows/rust.yml, CHANGELOG.md, contrib/bindings/python/Makefile, contrib/bindings/python/pathrs/.gitignore, contrib/bindings/python/pathrs/__init__.py, contrib/bindings/python/pathrs/_libpathrs_cffi/__init__.pyi, contrib/bindings/python/pathrs/_libpathrs_cffi/lib.pyi, contrib/bindings/python/pathrs/_pathrs.py, contrib/bindings/python/pathrs/pathrs_build.py, contrib/bindings/python/pyproject.toml, go-pathrs/root_linux.go, src/capi/ret.rs, src/root.rs, src/tests/capi/root.rs, src/tests/traits/root.rs
This is just a first pass, trying to make the annotations make sense. We
probably need to adjust some of them for packaging before the next
release.
The type annotations for libpathrs.so should be sufficient but it's a
bit unfortunate that ffi.NULL can't be listed as a possible return value
(a-la None with Optional). This makes the typing for errorinfo a little
dodgy, and the Error._fetch typing also is not entirely idiomatic (maybe
we need to have an overload to indicate that only actual ErrorIds return
an Error). It would be nice if we could do Literal[0..] but that syntax
doesn't exist.
=> python bindings: add type information and minor fixups

CHANGELOG.md, Cargo.toml, contrib/bindings/python/pyproject.toml
```
> 蛇のように賢く、鳩のように素直でありなさい
- python bindings: add a minimal README for PyPI.
- python bindings: actually export `PROC_ROOT`.
- python bindings: add type annotations and `py.typed` to allow for downstream
users to get proper type annotations for the API.
```
=> VERSION: release v0.1.2

CHANGELOG.md, Cargo.toml, contrib/bindings/python/pyproject.toml
```
> 自動化って物は試しとすればいい物だ
- gha: our Rust crate and Python bindings are now uploaded automatically from a
GitHub action when a tag is pushed.
- syscalls: the pretty-printing of `openat2` errors now gives a string
description of the flags passed rather that just a hex value (to match other
syscalls).
```
=> VERSION: release v0.1.3

src/capi/core.rs, src/handle.rs, src/resolvers/mod.rs, src/resolvers/openat2.rs, src/root.rs, src/tests/capi/handle.rs, src/tests/capi/root.rs, src/tests/test_root_ops.rs, src/tests/traits/handle.rs, src/tests/traits/root.rs
It seems incredibly unlikely that we will ever add verification to
Handle::from_fd / Root::from_fd, so having the _unchecked suffix doesn't
really make sense.
Fixes #85 
=> {Root,Handle}::from_fd_unchecked -> from_fd

Cargo.toml, src/capi/error.rs, src/lib.rs, src/procfs.rs, src/resolvers/mod.rs, src/resolvers/opath/impl.rs, src/syscalls.rs
Ideally we would switch to std::sync::LazyLock but that was only stabilised in Rust 1.80.0, so we have to make do with once_cell. At least once_cell has basically the same API as the merged-into-std API, so we can switch over very easily.
=> *: migrate from lazy_static! to once_cell::sync::Lazy

CHANGELOG.md, Cargo.toml, src/flags.rs, src/procfs.rs, src/resolvers/opath/impl.rs, src/resolvers/procfs.rs, src/root.rs, src/syscalls.rs, src/tests/common/mntns.rs, src/tests/common/root.rs, src/tests/test_procfs.rs, src/tests/test_root_ops.rs, src/utils/dir.rs, src/utils/fd.rs
Using libc leads to several issues when dealing with multiarch that make things quite frustrating, and rustix does provide nicer APIs (for the most part -- some are a little wonky). One major annoyance is that building for musl leads to annoying build failures because musl uses differently-sized or differently-signed types, which we don't want to care about because we just want to use the actual kernel APIs. Also, musl is missing wrappers for things like statx(2) which we need to use.
We still need syscall wrappers to provide nice error information, but we can remove most of the internal-only bitflags and unsafe blocks. The only syscall wrapper we don't switch to rustix is openat2 because rustix's API is not designed to be extensible and so we can stick with libc for now.
In the future we …
=> syscalls: switch to rustix for most of our syscalls

src/capi/core.rs, src/capi/procfs.rs, src/capi/utils.rs, src/tests/capi/handle.rs, src/tests/common/handle.rs, src/tests/test_procfs.rs, src/tests/test_root_ops.rs, src/tests/traits/handle.rs
It is incredibly easy to unset O_CLOEXEC using fcntl, and most users
should want O_CLOEXEC. This also matches how newer kernel APIs are
designed (where O_CLOEXEC is the default).
Fixes #120
=> capi: always apply O_CLOEXEC to returned file descriptors

CHANGELOG.md, src/capi/error.rs, src/error.rs, src/tests.rs, src/tests/capi/utils.rs, src/tests/common/error.rs, src/tests/common/handle.rs, src/tests/test_procfs.rs, src/tests/test_resolve.rs, src/tests/test_resolve_partial.rs, src/tests/test_root_ops.rs, src/utils/sysctl.rs
This primarily contains two useful fixes related to our error APIs:
* `capi: error: map pure-Rust errors into equivalent errno values` (#60)
* `errors: document and export ErrorKind` (#61)
From the changelog:
- Error: `ErrorKind` is now exported, allowing you to programmatically handle
errors returned by libpathrs. This interface may change in the future (in
particular, `ErrorKind::OsError` might change its representation of `errno`
values).
- capi: errors that are returned by libpathrs itself (such as invalid arguments
being passed by users) will now contain a `saved_errno` value that makes
sense for the error type (so `ErrorKind::InvalidArgument` will result in an
`EINVAL` value for `saved_errno`). This will allow C users to have a nicer
time handling errors programmatically.
Fixes #60 …
=> errors: improve error APIs

CHANGELOG.md, src/capi/error.rs, src/error.rs, src/root.rs, src/syscalls.rs, src/tests/test_root_ops.rs
If two programs are doing Root::mkdir_all, the previous logic would
return an error if a directory already existed once we got into the
"mkdir" portion of the creation.
Since we already have to accept that an attacker can swap the inode with
a different directory, returning -EEXIST from mkdirat(2) just causes
spurious errors. All we care about is that we open a directory.
Fixes #128 
=> Root: do not error out with EEXIST for racing Root::mkdir_all()s

.github/workflows/bindings-python.yml, contrib/bindings/python/Makefile, contrib/bindings/python/pathrs/__init__.py, contrib/bindings/python/pathrs/_libpathrs_cffi/lib.pyi, contrib/bindings/python/pathrs/_pathrs.py, contrib/bindings/python/pathrs/pathrs_build.py
ruff includes both black-like formatting as well as general linting
(which we were previously missing) and it is much faster than the
alternatives.
=> python bindings: switch to ruff linter

CHANGELOG.md, src/resolvers/openat2.rs, src/resolvers/procfs.rs, src/syscalls.rs
We should have always set O_NOCTTY, as with openat(2) because resolution
scoping flags don't affect the safety risks of opening PTYs.
As for auto-setting O_NOFOLLOW (and having openat2_follow), while
O_NOFOLLOW is safe when doing scoped lookups (RESOLVE_BENEATH and
RESOLVE_IN_ROOT), not every openat2 invocation is going to be using
scoped lookups. For safety, we should have the same scheme -- especially
since it's clear that we will always have these wrappers.
=> syscalls: openat2: mirror openat / openat_follow

CHANGELOG.md, src/capi/utils.rs, src/handle.rs, src/procfs.rs, src/resolvers.rs, src/resolvers/opath/imp.rs, src/resolvers/openat2.rs, src/resolvers/procfs.rs, src/root.rs, src/syscalls.rs, src/tests/capi/handle.rs, src/tests/capi/procfs.rs, src/tests/capi/root.rs, src/tests/capi/utils.rs, src/tests/common/handle.rs, src/tests/common/mntns.rs, src/tests/test_procfs.rs, src/tests/test_race_resolve_partial.rs, src/tests/test_resolve.rs, src/tests/test_resolve_partial.rs, src/tests/test_root_ops.rs, src/tests/traits/handle.rs, src/tests/traits/procfs.rs, src/tests/traits/root.rs, src/utils/dir.rs, src/utils/fd.rs
It turns out that taking `impl Trait` arguments is actually more ergonomic
in a lot of cases:
* It makes it easier to write APIs where the caller specifying a
generic type with `::<>` (like `str::parse::<T>`) much easier. If every
type parameter is named then you need to do `::<_, _, Foo, _>()` which
is awful.
* It avoids the need to define a generic type for each argument even if
they implement the same trait (`<P1: AsRef<Path>, P2: AsRef<Path>`).
This is needed to avoid annoying reference issues (and it turns out
that we missed fixing this in a few places).
* The rustdoc documentation generated looks much nicer -- it is far
clearer to users what types we accept (previously, the use of generic
type parameter names would require users to look at the where clause
to see what Trait impl is …
=> *: switch to impl Trait for most APIs

.github/workflows/rust.yml, Cargo.toml, Makefile, hack/rust-tests.sh, src/syscalls.rs, src/tests/test_procfs.rs, src/tests/test_race_resolve_partial.rs, src/tests/test_resolve.rs, src/tests/test_resolve_partial.rs, src/tests/test_root_ops.rs
This will allow us to test our code in a way that emulates kernels
without openat2 (or openat2 disabled with seccomp).
Rather than #[cfg(...)]-gating every bit of openat2 code, it is much
less messy to just make the underlying syscall wrapper return -ENOSYS
(which will then cause *OPENAT2_IS_SUPPORTED to be false). This will
also let us test -ENOSYS fallbacks. Though, we need to disallow the
KernelOpenat2 to stop things from explicitly requesting that resolver.
Also, now that we have default features we need to run checks and tests
with them disabled.
=> resolvers: add opt-out openat2 feature

.github/workflows/rust.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, hack/rust-tests.sh, src/error.rs, src/lib.rs, src/procfs.rs, src/resolvers/procfs.rs, src/root.rs, src/syscalls.rs, src/tests/test_procfs.rs, src/utils.rs, src/utils/fd.rs, src/utils/fdinfo.rs, src/utils/maybe_owned.rs, src/utils/path.rs, src/utils/raw_procfs.rs, src/utils/sysctl.rs
=> utils: use fdinfo as final fallback for fetch_mnt_id

src/utils/raw_procfs.rs
Because RawProcfsHandle is only used for fdinfo/$n opens, we really
should be auto-applying O_NOFOLLOW. The only slightly odd point is that
the non-openat2 codepath splits the open into O_PATH and re-open, so we
need to handle O_NOFOLLOW a little differently.
=> raw procfs: use O_NOFOLLOW for all fdinfo opens
